### ISSUE TITLE
"fist-fit" meaning?

### ISSUE THREAD

**Issue by JamesBremner** [quartermaine/k8_resource_allocation#1]
Does "fist-fit" mean "first-fit"?

https://github.com/quartermaine/k8_resource_allocation/blob/main/fist_fit.cpp

What is the meaning of "k8_resource_allocation"

**Comment by quartermaine** [comment]
Hello James,

Thank for noticing the mistake. 
The k8 is referring to kubernetes as this was my original problem on how to distribute pods to nodes.

**Comment by JamesBremner** [comment]
But you still have not fixed the mistake.  It is now two days ...

**Comment by JamesBremner** [comment]
... now 3 days and still nothing.  Do you intend to fix this mistake?  If not, you should say so.
